### ISSUE TITLE
How do I format the strings generated?

### ISSUE THREAD

**Issue by samseen** [mkropat/MlkPwgen#11]
Hello, how can I generate a password that will be only 10 letters and will be a combination of Uppercase characters, Lowercase characters, Numbers, Symbol and also pronounceable. 

Here's what I've done so far: 
```
//Generate Password
var password = PasswordGenerator.Generate(length: 10, allowed: Sets.Alphanumerics);
var thePassword = password + "2#";
```
I can't figure out how to use this... in C# after checking the readme. The alphanumeric can sometimes all be lowercase and I don't want this to happen.
Looking forward to your guidance.

**Comment by mkropat** [comment]
Good question. The documentation for the .NET library isn't the best.

If you want a password that can guarantee complexity requirements, try this:

```csharp
var password = PasswordGenerator.GenerateComplex(
  length: 10,
  requiredSets: new[] { Sets.Lower, Sets.Upper, Sets.Digits, Sets.Symbols }
);
```

If you want it to also be pronounceable, try this:

```csharp
var password = PronounceableGenerator.Generate(
  length: 10,
  requiredSets: new[] { Sets.Lower, Sets.Upper, Sets.Digits, Sets.Symbols }
);
```
