### ISSUE TITLE
.netcore support

### ISSUE THREAD

**Issue by ahmad-moussawi** [mkropat/MlkPwgen#4]
Any support planned for .netcore ?

**Comment by mkropat** [comment]
Good idea. Thanks for the suggestion.

It was quite easy to get the library compiling for .netcore. I made a PR (#5) with the work in progress.

However, I am ignorant of how .netcore `.dll`'s work and interact with the non-.netcore world, so I documented (on #5) a number of open questions I need to research before merging/releasing any of these changes.

**Comment by mkropat** [comment]
Basic .netcore support is now implemented in the latest release:

https://www.nuget.org/packages/MlkPwgen/0.3.0

I've only tested the .netcore support lightly, so if anyone runs into any issues, please let me know by submitting a new issue.
